# Generated by Django 2.1.2 on 2018-11-27 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('c_no', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sc_score', models.IntegerField(max_length=3)),
                ('sc_cno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('s_no', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('s_name', models.CharField(max_length=32)),
                ('s_sex', models.CharField(max_length=3)),
                ('s_age', models.IntegerField(max_length=3)),
                ('s_class', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='score',
            name='sc_sno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Student'),
        ),
    ]
