# Generated by Django 2.1.2 on 2018-11-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pub_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='score',
            name='pub_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='student',
            name='pub_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='sc_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_age',
            field=models.IntegerField(),
        ),
    ]
