# Generated by Django 2.1.2 on 2018-11-28 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20181127_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('user_password', models.CharField(max_length=3)),
            ],
        ),
    ]
