# Generated by Django 2.1.2 on 2018-11-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pub_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
